### ISSUE TITLE
Rooms API

### ISSUE THREAD

**Issue by antonkomarev** [secusu/secusu#14]
# Define connection

``` js
var chat = io.connect({WS_HOSTNAME} + ':' + {WS_PORT} + '/r', {secure: true})
```
# Create room

``` js
chat.emit('room.create', {
    password: '{PASSWORD}'
});
```

On success:
- room is created;
- the room's hash is sent to the client;
- the provided password is encrypted using `bcrypt` and saved as `room.password` in database;

**After that client should manually perform `Join room` using password again.**
### Success events

``` js
chat.on('room.create', {
    success: true,
    room: '{ROOM_NAME}'
});
```
### Fail events

``` js
chat.on('room.create', {
    success: false,
    errors: ['Error message 1', 'Error message 2']
});
```
# Join room

``` js
chat.emit('room.join', {
    room: '{ROOM_NAME}',
    password: '{PASSWORD}'
});
```
### Success events

**Name:** `room.join`
**Recipients:** Initiator
**Description:** User receives self state in room.

``` js
chat.on('room.join', {
    success: true,
    name: user.name
})
```

**Name:** `room.roster`
**Recipients:** Active room users (including initiator)
**Description:** All users in room receives updated room roster as users objects.

``` js
chat.on('room.roster', [
    {name: "User 1"},
    {name: "User 2"}
])
```
### Fail events

**Name:** `room.join`
**Recipients:** Initiator
**Description:** User informed that authentication has been failed.

``` js
chat.on('room.join', {
    success: false,
    room: room
});
```

**Name:** `room.join.attempt`
**Recipients:** Active room users
**Description:** All users in room receives information that somebody has failed authentication.

``` js
chat.on('room.join.attempt', {
    success: false,
    room: room,
    errors: ['Somebody tried to join room with empty password']
});
```
# Leave room

``` js
chat.emit('room.leave' {
    room: '{ROOM_NAME}'
});
```
### Success events

**Name:** `room.leave`
**Recipients:** Initiator
**Description:** User receives info that he left the room.

``` js
chat.on('room.leave', {
    success: true
})
```

**Name:** `room.roster`
**Recipients:** Active room users
**Description:** All users in room receives updated room roster as users objects.

``` js
chat.on('room.roster', [
    {name: "User 1"},
    {name: "User 2"}
])
```
### Fail events

``` js
chat.on('room.leave', {
    success: false,
    errors: ['Empty arguments']
});
```
# Send message

``` js
chat.emit('room.data', {
    room: '{ROOM_NAME}',
    data: 'STRING'
});
```
### Success events

``` js
chat.on('room.data', {
    success: true,
    sender: '{USER_NAME}',
    data: '{JSON_DATA}'
});
```
### Fail events

``` js
chat.on('room.data', {
    success: false,
    errors: ['Empty arguments']
});
```

``` js
chat.on('room.data.attempt', {
    success: false,
    errors: ['Somebody tried to send message without authorization']
});
```

**Comment by a-komarev** [comment]
# Events

| Channel | Event | Reason |
| ---------- | -------- | --------- |
|  `private-room-{HASH}` | `\\App\\Events\\Room\\NewMessage` | Somebody sent message |
| `private-room-{HASH}` |  `\\App\\Events\\Room\\MessageRejected` | Incorrect token provided |

**Comment by a-komarev** [comment]
Additional commands (future planning).

#  (draft) Lock room

```js
PUT `/r/{HASH}/lock
{
    token: '{TOKEN}'
}
```

#  (draft) Unlock room

```js
PUT `/r/{HASH}/unlock
{
    token: '{TOKEN}'
}
```

#  (draft) Change name

```js
PUT `/r/{HASH}/name
{
    token: '{TOKEN}',
    name: 'STRING'
}
```

Name change will be affected only on current room.
